In [19]:
import numpy as np

In [22]:
a=np.array([0,1,2,3,4])#list

In [23]:
a

array([0, 1, 2, 3, 4])

In [24]:
c=np.arange(1,5,2)#开始，结束，步长

In [25]:
c

array([1, 3])

In [26]:
d=np.linspace(0,2*np.pi,5)#开始，结束，个数

In [27]:
d

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531])

In [29]:
e=np.array([[11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
           ])#二维

In [30]:
e

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
e[2,4]#切片

25

In [33]:
e.shape#行数，列数

(4, 5)

In [34]:
e[0,1:2]#切片

array([12])

In [35]:
type(e)

numpy.ndarray

In [40]:
e.dtype#维度数据类型

dtype('int64')

In [41]:
e.size

20

In [42]:
e.shape

(4, 5)

In [43]:
e.ndim#维度数

2