In [19]:
import numpy as np

In [22]:
a=np.array([0,1,2,3,4])#list

In [23]:
a

array([0, 1, 2, 3, 4])

In [24]:
c=np.arange(1,5,2)#开始，结束，步长

In [25]:
c

array([1, 3])

In [26]:
d=np.linspace(0,2*np.pi,5)#开始，结束，个数

In [27]:
d

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531])

In [29]:
e=np.array([[11,12,13,14,15],
            [16,17,18,19,20],
            [21,22,23,24,25],
            [26,27,28,29,30]
           ])#二维

In [30]:
e

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
e[2,4]#切片

25

In [33]:
e.shape#行数，列数

(4, 5)

In [34]:
e[0,1:2]#切片

array([12])

In [35]:
type(e)

numpy.ndarray

In [40]:
e.dtype#维度数据类型

dtype('int64')

In [41]:
e.size

20

In [42]:
e.shape

(4, 5)

In [43]:
e.ndim#维度数

2

In [45]:
a=np.arange(25)

In [46]:
a=a.reshape((5,5))

In [47]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
b=np.array(np.random.randint(1,25,25))

In [54]:
b

array([ 5,  7,  2, 11, 12,  1, 11, 14,  3, 12, 11, 10, 18,  1, 15,  7, 10,
       12, 11, 20,  1, 16, 16, 15, 13])

In [55]:
np.random.randint(25)

2

In [56]:
np.random.randint?

In [59]:
b=b.reshape((5,5))

In [60]:
a+b

array([[ 5,  8,  4, 14, 16],
       [ 6, 17, 21, 11, 21],
       [21, 21, 30, 14, 29],
       [22, 26, 29, 29, 39],
       [21, 37, 38, 38, 37]])

In [61]:
a**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [63]:
a.dot(b)#矩阵乘法

array([[  48,  125,  150,   98,  154],
       [ 173,  395,  460,  303,  514],
       [ 298,  665,  770,  508,  874],
       [ 423,  935, 1080,  713, 1234],
       [ 548, 1205, 1390,  918, 1594]])

In [64]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
a=np.arange(10)

In [67]:
a.sum()

45

In [68]:
a.min()

0

In [69]:
a.max()

9

In [70]:
a.cumsum()#累积和

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [71]:
a=np.arange(0,100,10)

In [72]:
indices=[1,5,-1]

In [73]:
b=a[indices]